version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: givemethatsewon/stock-diary-api:latest
    container_name: stock-diary-api
    restart: unless-stopped
    environment:
      # DB
      DATABASE_URL: ${DATABASE_URL}
      # JWT
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      # Firebase
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/firebase_credentials
      # OpenAI
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # AWS
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # Misc
      ENVIRONMENT: ${ENVIRONMENT:-development}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
    ports:
      - "8000:8000"
    volumes:
      - ${FIREBASE_CREDENTIALS_FILE:-./stock-diary-firebase-credentials.json}:/run/secrets/firebase_credentials:ro
    networks:
      - stock-diary-net

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID}
    image: givemethatsewon/stock-diary-web:latest
    container_name: stock-diary-web
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      INTERNAL_API_URL: http://api:8000
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - stock-diary-net

volumes:
  db_data:


networks:
  stock-diary-net:
    driver: bridge



